name: Build ETL Runner

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build:
    uses: zavestudios/platform-pipelines/.github/workflows/container-build.yml@main
    with:
      image_name: ${{ github.repository_owner }}/zavestudios-etl-runner
      dockerfile: Dockerfile
      push: ${{ github.ref == 'refs/heads/main' }}
      platforms: linux/amd64
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
